# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 只想做个明白人
email: explorerlxz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    看书、看書、read books…
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://explorerlxz.github.io" # the base hostname & protocol for your site
twitter_username: explorerlxz
github_username:  explorerlxz
images:
    background:url(/images/background.jpg)
# Build settings
markdown: kramdown
