# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 無生忍
email: explorerlxz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    學佛乃大丈夫事，非帝王將相所能爲
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://explorerlxz.github.io" # the base hostname & protocol for your site
twitter_username: explorerlxz
github_username: explorerlxz 
images:
    #  
# Build settings
highlighter: rouge
markdown: kramdown

linenos: true

highlight:
    linenos: true

krandown:
    input: GFM
    syntax_highlighter: rouge
#markdown: rdiscount
