# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 距离练成八块腹肌&人鱼线还剩79天（2016-07-31～2016-10-18）
email: explorerlxz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    获得财富会失去良心，获得爱情会失去理智;发现真相会失去信仰，只有失去一切才会获得自由。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://explorerlxz.github.io" # the base hostname & protocol for your site
twitter_username: explorerlxz
github_username: explorerlxz 
images:
    #    background:url(https://explorerlxz.github.io/images/background.jpg)
# Build settings
markdown: kramdown
